/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'cloud-photos': CloudPhoto;
    'cloud-documents': CloudDocument;
    'web-pages': WebPage;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'cloud-photos' | 'cloud-documents';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'cloud-photos': CloudPhotosSelect<false> | CloudPhotosSelect<true>;
    'cloud-documents': CloudDocumentsSelect<false> | CloudDocumentsSelect<true>;
    'web-pages': WebPagesSelect<false> | WebPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'web-landing': WebLanding;
    'web-navigation': WebNavigation;
    'web-footer': WebFooter;
    'web-settings': WebSetting;
  };
  globalsSelect: {
    'web-landing': WebLandingSelect<false> | WebLandingSelect<true>;
    'web-navigation': WebNavigationSelect<false> | WebNavigationSelect<true>;
    'web-footer': WebFooterSelect<false> | WebFooterSelect<true>;
    'web-settings': WebSettingsSelect<false> | WebSettingsSelect<true>;
  };
  locale: 'es' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloud-photos".
 */
export interface CloudPhoto {
  id: number;
  alt: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'cloud-photos';
          value: number | CloudPhoto;
        }
      | {
          relationTo?: 'cloud-documents';
          value: number | CloudDocument;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('cloud-photos' | 'cloud-documents')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloud-documents".
 */
export interface CloudDocument {
  id: number;
  alt: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-pages".
 */
export interface WebPage {
  id: number;
  title: string;
  /**
   * A brief description of the page for SEO purposes. Max. 150 characters.
   */
  description?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  content?:
    | (
        | {
            title?: string | null;
            description?: string | null;
            images?: {
              main?: (number | null) | CloudPhoto;
              secondary?: (number | null) | CloudPhoto;
            };
            breakout?: {
              title?: string | null;
              description?: string | null;
              image?: (number | null) | CloudPhoto;
              button?: {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
              };
            };
            companies?: {
              title?: string | null;
              logo?: (number | CloudPhoto)[] | null;
            };
            achievements?: {
              title?: string | null;
              description?: string | null;
              items?:
                | {
                    label?: string | null;
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-about-03';
          }
        | {
            awards?:
              | {
                  name?: string | null;
                  year?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-award-01';
          }
        | {
            title?: string | null;
            defaultVisible?: boolean | null;
            description?: string | null;
            link?: {
              isExternal?: boolean | null;
              linkLabel?: string | null;
              linkUrl?: string | null;
              page?: (number | null) | WebPage;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-banner-01';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  author?: string | null;
                  role?: string | null;
                  logo?: (number | null) | CloudPhoto;
                  thumbnail?: (number | null) | CloudPhoto;
                  quote?: string | null;
                  stats?: {
                    items?:
                      | {
                          title?: string | null;
                          subtitle?: string | null;
                          value?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-case-studies-02';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            social?:
              | {
                  network?:
                    | (
                        | 'twitter'
                        | 'facebook'
                        | 'instagram'
                        | 'linkedin'
                        | 'tiktok'
                        | 'whatsapp'
                        | 'youtube'
                        | 'discord'
                        | 'github'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-community-01';
          }
        | {
            badge?: string | null;
            title?: string | null;
            description?: string | null;
            certifications?: (number | CloudPhoto)[] | null;
            highlights?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: (number | null) | CloudPhoto;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-compliance-01';
          }
        | {
            heading?: string | null;
            description?: string | null;
            buttons?: {
              primary?: {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
              };
              secondary?: {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-cta-10';
          }
        | {
            heading?: string | null;
            description?: string | null;
            image?: (number | null) | CloudPhoto;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-cta-11';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question?: string | null;
                  answer?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-faq-01';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            buttons?:
              | {
                  isExternal?: boolean | null;
                  linkLabel?: string | null;
                  linkUrl?: string | null;
                  page?: (number | null) | WebPage;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | CloudPhoto;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-hero-01';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'cloud-photos';
        value: number | CloudPhoto;
      } | null)
    | ({
        relationTo: 'cloud-documents';
        value: number | CloudDocument;
      } | null)
    | ({
        relationTo: 'web-pages';
        value: number | WebPage;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloud-photos_select".
 */
export interface CloudPhotosSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloud-documents_select".
 */
export interface CloudDocumentsSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-pages_select".
 */
export interface WebPagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  content?:
    | T
    | {
        'block-about-03'?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    main?: T;
                    secondary?: T;
                  };
              breakout?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    button?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                        };
                  };
              companies?:
                | T
                | {
                    title?: T;
                    logo?: T;
                  };
              achievements?:
                | T
                | {
                    title?: T;
                    description?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'block-award-01'?:
          | T
          | {
              awards?:
                | T
                | {
                    name?: T;
                    year?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-banner-01'?:
          | T
          | {
              title?: T;
              defaultVisible?: T;
              description?: T;
              link?:
                | T
                | {
                    isExternal?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    page?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-case-studies-02'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    author?: T;
                    role?: T;
                    logo?: T;
                    thumbnail?: T;
                    quote?: T;
                    stats?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                title?: T;
                                subtitle?: T;
                                value?: T;
                                id?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-community-01'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              social?:
                | T
                | {
                    network?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-compliance-01'?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              certifications?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-cta-10'?:
          | T
          | {
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    primary?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                        };
                    secondary?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'block-cta-11'?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'block-faq-01'?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-hero-01'?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    isExternal?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    page?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-landing".
 */
export interface WebLanding {
  id: number;
  content?:
    | (
        | {
            title?: string | null;
            description?: string | null;
            images?: {
              main?: (number | null) | CloudPhoto;
              secondary?: (number | null) | CloudPhoto;
            };
            breakout?: {
              title?: string | null;
              description?: string | null;
              image?: (number | null) | CloudPhoto;
              button?: {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
              };
            };
            companies?: {
              title?: string | null;
              logo?: (number | CloudPhoto)[] | null;
            };
            achievements?: {
              title?: string | null;
              description?: string | null;
              items?:
                | {
                    label?: string | null;
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-about-03';
          }
        | {
            awards?:
              | {
                  name?: string | null;
                  year?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-award-01';
          }
        | {
            title?: string | null;
            defaultVisible?: boolean | null;
            description?: string | null;
            link?: {
              isExternal?: boolean | null;
              linkLabel?: string | null;
              linkUrl?: string | null;
              page?: (number | null) | WebPage;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-banner-01';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  author?: string | null;
                  role?: string | null;
                  logo?: (number | null) | CloudPhoto;
                  thumbnail?: (number | null) | CloudPhoto;
                  quote?: string | null;
                  stats?: {
                    items?:
                      | {
                          title?: string | null;
                          subtitle?: string | null;
                          value?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-case-studies-02';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            social?:
              | {
                  network?:
                    | (
                        | 'twitter'
                        | 'facebook'
                        | 'instagram'
                        | 'linkedin'
                        | 'tiktok'
                        | 'whatsapp'
                        | 'youtube'
                        | 'discord'
                        | 'github'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-community-01';
          }
        | {
            badge?: string | null;
            title?: string | null;
            description?: string | null;
            certifications?: (number | CloudPhoto)[] | null;
            highlights?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: (number | null) | CloudPhoto;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-compliance-01';
          }
        | {
            heading?: string | null;
            description?: string | null;
            buttons?: {
              primary?: {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
              };
              secondary?: {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-cta-10';
          }
        | {
            heading?: string | null;
            description?: string | null;
            image?: (number | null) | CloudPhoto;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-cta-11';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question?: string | null;
                  answer?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-faq-01';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            buttons?:
              | {
                  isExternal?: boolean | null;
                  linkLabel?: string | null;
                  linkUrl?: string | null;
                  page?: (number | null) | WebPage;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | CloudPhoto;
            id?: string | null;
            blockName?: string | null;
            blockType: 'block-hero-01';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-navigation".
 */
export interface WebNavigation {
  id: number;
  position?: ('left' | 'center' | 'right') | null;
  navItems?:
    | {
        label: string;
        page?: (number | null) | WebPage;
        subItems?:
          | (
              | {
                  items: {
                    page: number | WebPage;
                    showDescription?: boolean | null;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'subitem-default';
                }
              | {
                  items: {
                    page: number | WebPage;
                    showDescription?: boolean | null;
                    isHighlighted?: boolean | null;
                    bgImage?: (number | null) | CloudPhoto;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'subitem-expanded';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-footer".
 */
export interface WebFooter {
  id: number;
  block: {
    navLinks?:
      | {
          group: string;
          links?:
            | {
                isExternal?: boolean | null;
                linkLabel?: string | null;
                linkUrl?: string | null;
                page?: (number | null) | WebPage;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'web-footer-6';
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-settings".
 */
export interface WebSetting {
  id: number;
  general?: {
    name?: string | null;
    /**
     * A brief description of the website for SEO purposes.
     */
    description?: string | null;
    /**
     * The site icon is what you see in browser tabs and bookmarks bars. It should be square and at least 512 by 512 pixels.
     */
    icon?: (number | null) | CloudPhoto;
    /**
     * The site logo is used in the website header and footer.
     */
    logo?: (number | null) | CloudPhoto;
  };
  styles?: {
    radius?: number | null;
    font?: {
      key?: string | null;
      family?: string | null;
    };
    brand?: {
      bg?: string | null;
      fg?: string | null;
      palette?: {
        '50'?: string | null;
        '100'?: string | null;
        '200'?: string | null;
        '300'?: string | null;
        '400'?: string | null;
        '500'?: string | null;
        '600'?: string | null;
        '700'?: string | null;
        '800'?: string | null;
        '900'?: string | null;
        '950'?: string | null;
      };
    };
    secondary?: {
      bg?: string | null;
      fg?: string | null;
      palette?: {
        '50'?: string | null;
        '100'?: string | null;
        '200'?: string | null;
        '300'?: string | null;
        '400'?: string | null;
        '500'?: string | null;
        '600'?: string | null;
        '700'?: string | null;
        '800'?: string | null;
        '900'?: string | null;
        '950'?: string | null;
      };
    };
  };
  social?: {
    contact?: {
      email?: string | null;
      /**
       * Type only numbers and the "+" sign. Example: +1234567890. No spaces or dashes. Proper formatting will be applied automatically.
       */
      phone?: string | null;
    };
    networks?: {
      twitter?: string | null;
      facebook?: string | null;
      instagram?: string | null;
      linkedin?: string | null;
      tiktok?: string | null;
      whatsapp?: string | null;
      youtube?: string | null;
      discord?: string | null;
      github?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-landing_select".
 */
export interface WebLandingSelect<T extends boolean = true> {
  content?:
    | T
    | {
        'block-about-03'?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    main?: T;
                    secondary?: T;
                  };
              breakout?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    button?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                        };
                  };
              companies?:
                | T
                | {
                    title?: T;
                    logo?: T;
                  };
              achievements?:
                | T
                | {
                    title?: T;
                    description?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'block-award-01'?:
          | T
          | {
              awards?:
                | T
                | {
                    name?: T;
                    year?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-banner-01'?:
          | T
          | {
              title?: T;
              defaultVisible?: T;
              description?: T;
              link?:
                | T
                | {
                    isExternal?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    page?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-case-studies-02'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    author?: T;
                    role?: T;
                    logo?: T;
                    thumbnail?: T;
                    quote?: T;
                    stats?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                title?: T;
                                subtitle?: T;
                                value?: T;
                                id?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-community-01'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              social?:
                | T
                | {
                    network?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-compliance-01'?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              certifications?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-cta-10'?:
          | T
          | {
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    primary?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                        };
                    secondary?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'block-cta-11'?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'block-faq-01'?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'block-hero-01'?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    isExternal?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    page?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-navigation_select".
 */
export interface WebNavigationSelect<T extends boolean = true> {
  position?: T;
  navItems?:
    | T
    | {
        label?: T;
        page?: T;
        subItems?:
          | T
          | {
              'subitem-default'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          page?: T;
                          showDescription?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              'subitem-expanded'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          page?: T;
                          showDescription?: T;
                          isHighlighted?: T;
                          bgImage?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-footer_select".
 */
export interface WebFooterSelect<T extends boolean = true> {
  block?:
    | T
    | {
        'web-footer-6'?:
          | T
          | {
              navLinks?:
                | T
                | {
                    group?: T;
                    links?:
                      | T
                      | {
                          isExternal?: T;
                          linkLabel?: T;
                          linkUrl?: T;
                          page?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-settings_select".
 */
export interface WebSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        name?: T;
        description?: T;
        icon?: T;
        logo?: T;
      };
  styles?:
    | T
    | {
        radius?: T;
        font?:
          | T
          | {
              key?: T;
              family?: T;
            };
        brand?:
          | T
          | {
              bg?: T;
              fg?: T;
              palette?:
                | T
                | {
                    '50'?: T;
                    '100'?: T;
                    '200'?: T;
                    '300'?: T;
                    '400'?: T;
                    '500'?: T;
                    '600'?: T;
                    '700'?: T;
                    '800'?: T;
                    '900'?: T;
                    '950'?: T;
                  };
            };
        secondary?:
          | T
          | {
              bg?: T;
              fg?: T;
              palette?:
                | T
                | {
                    '50'?: T;
                    '100'?: T;
                    '200'?: T;
                    '300'?: T;
                    '400'?: T;
                    '500'?: T;
                    '600'?: T;
                    '700'?: T;
                    '800'?: T;
                    '900'?: T;
                    '950'?: T;
                  };
            };
      };
  social?:
    | T
    | {
        contact?:
          | T
          | {
              email?: T;
              phone?: T;
            };
        networks?:
          | T
          | {
              twitter?: T;
              facebook?: T;
              instagram?: T;
              linkedin?: T;
              tiktok?: T;
              whatsapp?: T;
              youtube?: T;
              discord?: T;
              github?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}